### ISSUE TITLE
Something wrong when launch iplanner. process has died

### ISSUE THREAD

**Issue by JACKLiuDay** [leggedrobotics/iPlanner#1]
Hi, thank you for your great job about iplanner. I tried the iplanner with the garage simulation env. But when i set the waypoint, the robot runs to the point then the program died. Could you give me some advice?
![image](https://github.com/leggedrobotics/iPlanner/assets/30967867/e80acd82-2300-4978-9874-95d237b44ba4)

**Comment by xiaomengfang** [comment]
I had the same problem, only the first goal could be successfully planned. How did you fix it?

**Comment by JACKLiuDay** [comment]
> I had the same problem, only the first goal could be successfully planned. How did you fix it?

Hi, try iplanner without rviz.
