### ISSUE TITLE
This doesn't work properly with catkin make

### ISSUE THREAD

**Issue by ChaselLau666** [leggedrobotics/iPlanner#7]
![image](https://github.com/leggedrobotics/iPlanner/assets/139679124/29a3fda1-02be-41c0-a2a2-29c2540c097e)

**Comment by 942411526** [comment]
@ChaselLau666 Hi,
I have this problem, How do you deal with this problem?

**Comment by ChaselLau666** [comment]
mkdir a new catkin_ws , put it into src and cd .. catkin_make you can learn about workspace in ros

**Comment by 942411526** [comment]
> mkdir a new catkin_ws , put it into src and cd .. catkin_make you can learn about workspace in ros

thanks for your reply, but I can't build the iplanner_node. Can you tell me in detail?

**Comment by 942411526** [comment]
> mkdir a new catkin_ws , put it into src and cd .. catkin_make you can learn about workspace in ros

it work,but roslaunch iplanner_node data_collector.launch without any data

**Comment by 942411526** [comment]
> > mkdir a new catkin_ws , put it into src and cd .. catkin_make you can learn about workspace in ros
> 
> it work,but roslaunch iplanner_node data_collector.launch without any data

Wait to get camera extrinsic

**Comment by GuoErXing** [comment]
> > > mkdir a new catkin_ws , put it into src and cd .. catkin_make you can learn about workspace in ros
> > 
> > 
> > it work,but roslaunch iplanner_node data_collector.launch without any data
> 
> Wait to get camera extrinsic

I have the same problem, and I read your previous response but still don't understand how to proceed. Can you tell me in detail?
